name: flutter_zlapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #插件地址 https://pub.dev/packages
  cupertino_icons: ^0.1.2
  #
  cached_network_image: 1.1.1
  #轮播图第三方
  flutter_swiper: ^1.1.6
  #数据请求
  dio: ^2.1.3
  #本地存储
  shared_preferences: ^0.5.4+3
  #文件存储
  sqflite: ^1.0.0
  #刷新
  pull_to_refresh: ^1.5.7
  #瀑布流
  flutter_staggered_grid_view: ^0.3.0
  # 微光效果控件
  shimmer: ^1.0.1
#  当我们想在多个页面（组件/Widget）之间共享状态（数据），或
#  者一个页面（组件/Widget）中的多个子组件之间共享状态（数据），这个时候我们就可以
#  用 Flutter 中的状态管理来管理统一的状态（数据），实现不同组件直接的传值和数据共享。
#  那么这一讲给大家讲的 event_bus 主要是实现不同组件之间的数据传值，以及在一个组件中
#  执行另一个组件的方法。
  event_bus: ^1.1.0
  #Flutter 的日期选择器控件，iOS 样式。
  flutter_cupertino_date_picker: ^1.0.12
  #添加Provider依赖 状态管理
  provider: ^2.0.1+1
  #路由跳转
  fluro: ^1.5.1


  
  #弹出框 例如错误信息
  fluttertoast: ^3.0.3
  #model 生成 json解析
  json_annotation: ^2.0.0
  json_serializable: ^2.0.0 # 解析
  build_runner: ^1.1.2 # 解析
  # 加载提示组件
  flutter_spinkit: ^2.1.0
  #日期转换
  date_format: ^1.0.6
  #webview官方插件
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
      #就是高版本的flutter hello world工程创建时会自动依赖flutter_test的高版本，但是这个高版本的flutter_test和这个库的当前不兼容，所以会报错，删除掉test的引用或等待兼容性更新,
  # build_runner: ^1.1.2
  # json_serializable: ^2.0.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/oneAPP/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
